---
title: "Cox Proportional Hazard Model"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---
Study the Cox Proportional hazard model using healthcare example, learned from  [online resource](https://www.youtube.com/watch?v=3gXTkL2uVGU)

<div style="background-color:white;color:blue;matrixOperation:20px;">
### Hazard Ratio
</div>

We define the Hazard Ratio (HR) as:
$$HR = \frac{H_{treatment}}{H_{control}}$$
where $H$ - hazard rate refers to the probability of the event.


* HR = 0.5: at any particular time, half as many patients in the treatment group are experiencing an event compared to the controled group
* HR = 1: at any particular time, the event rates are the same in both groups
* HR = 2: at any particular time, twice as many patients in the treatment group are experiencing an event compared to the controled group

In another words, the shape of the hazard function is the same for all individuals, and only a scalar multiple changes per individual.

$$H_i(t) = \alpha_i H_0(t)$$
At the core of the assumption is that $\alpha_i$ does not change over time. Therefore, the hazard ratio is constant accross time

$$\frac{H_i(t)}{H_j(t)} = \frac{\alpha_i H_0(t)}{\alpha_j H_0(t)} = \frac{\alpha_i}{\alpha_j} $$




The mathematical formula resembles that of linear regression & logistic regression.

$$H(t) = H_0(t) \cdot e^{b_1X_1+b_2X_2+....b_kX_k}$$

By dividing both sides of the above equation by $H_0(t)$, and take log, we get:
$$ln(\frac{H(t)}{H_0(t)}) = b_1X_1+b_2X_2+....b_kX_k$$

Let's compare it with the logistic regression:
$$ln(\frac{\hat p}{1-\hat p}) = b_1X_1+b_2X_2+....b_kX_k$$
or expressed the logistic as odds ratio:

$$ln(Odds \ Ratio) = b_1X_1+b_2X_2+....b_kX_k$$

<div style="background-color:white;color:blue;matrixOperation:20px;">
### Model Assumptions
</div>

* Independence of survival times between distinct individuals in the sample
* A multiplicative relationship between the predicators and the hazard (as opposed to a linear one for multiple linear regression (OLS))
* A constant Hazard Ratio (HR) over time (proportional hazards assumption)!!!

<div style="background-color:white;color:blue;matrixOperation:20px;">
### Schoenfeld residuals
</div>
Schoenfeld residuals is used for testing the assumption of constant Hazard Ratio.

