---
title: "Credit Risk Models Comparison"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    includes:
      in_header: GA_Script.html
---

This page is for comparison of different credit risk models that used for Allowance for loan and lease losses (ALLL) purposes and if they can also be used for other regulatory purposes.


### 1. Roll rate model

Pros:

* Can see the evolution of the balance rolling for 1 bucket to the next which can be useful for understanding how the delinquency rate will move in the forecast.
* The calibration can be very straight-forward.
* The model forecast the loss rate directly, so there is no need to build separate models for PD and EAD.


Cons:

* Not easy to incorporate economic indicators into the model, which is required in the new CECL, IFRS 9, and CCAR regulation.
* The pros is also it's cons. The model does not segregate the loss to PD and EAD. For IFRS 9, it is not desirable since to measure if there is "increase in lifetime default risk", one needs to know the PD instead of the loss rate.
* The property of the transition matrix is memoryless. The DPD state information already contains all the information. How the balance changed before it become the current DPD state is irrelevant. This might not be true, since intuitively, a balance that is cured from 60+ to 30+ should be different from a balance that went from current to 30+. 
* Needs segregation of product charastistics and risk. There might be a lot of transition matrics needed to be calibrated and there might not be enough data.


### 2. Cox proportional hazard ratio


Pros:

* The model gives the whole PD curve as a function of age so it's easy to get the 12-month PD and lifetime PD which is an advantage for IFRS 9.
* Survival model is widely used not only in Finance but also other medical research area.


Cons:

* The survival model is just the PD model. EAD model has to be built separately.
* The assumption of constant hazard ratio (such that the shape of the curve should be similar when changing explanatory variables) is likely to be breached if the left censor point is the reporting date and day past due is one of the explanatory variable. It should work better for forecasting at the origination date.
* Difficult to incorporate economic indicator.


### 3. Discrete time survival model


Pros:

* Don't need the assumption of constant hazard ratio like the CoxPH model, so it can forecast at the reporting date and use delinquency information.
* Easy to incorporate economic indicators into the model.
* Easy to get the 12-month PD and lifetime (remaining life) PD for IFRS 9 purpose.

Cons:

* Needs a separate EAD model.
* Needs some heavy lifting in coding to build models for each period since reporting date.

### 4. Rating migration odel


Pros:

* Since most of the large financial institution build the IRB model for Basel, it can leverage rating from the IRB rating system.
* The model framework is the classical PD * EAD * LGD

Cons:

* Require separate PD, EAD and LGD models
* Need to adjust for conservatism if the IRB model for Basel is used as the underlying rating system.


