---
title: "IFRS 9 Requirements"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
bibliography: references.bib
link-citations: yes
---


### 1. Overview

Under the IFRS 9, published by ISAB, the lender should reserve for the loan loss based on different stages the loans are in.


* **Stage 1:** Initial recognition. Lender is required to reserve for the expected credit loss (ECL) that are expected to occur over the next **12-month** period.
* **Stage 2:** If a loan’s credit risk has increased significantly since initial recognition and is not considered low anymore, **lifetime** ECL should be recognised. The calculation of interest revenue is the same as for Stage 1. To emphasize, the wording 'increase significantly' is a comparison of the default risk at reporting date **relative** to initianl recognition date. 
* **Stage 3:**  If the loan’s credit risk increases to the point where it is considered **credit-impaired**, interest revenue is calculated based on the loan’s **amortised cost** (gross carrying amount minus loss allowance). Lifetime ECLs are recognised.


### 2. Significant increase in credit risk (SICR)
The summary of significant increase in credit risk is discussed the the following bullet points with corresponding text from the regulatory document and references.

* Significant increase in the **Lifetime Default Risk** as opposed to lifetime expected credit loss. 

  $\to$ see [@IFRS9] 5.5.9: *"At each reporting date, an entity shall assess whether the credit risk on a financial instrument has increased significantly since initial recognition. When making the assessment, an entity shall use the change in the risk of a default occurring over the expected life of the financial instrument instead of the change in the amount of expected credit losses. To make that assessment, an entity shall compare the risk of a default occurring on the financial instrument as at the reporting date with the risk of a default occurring on the financial instrument as at the date of initial recognition and consider reasonable and supportable information, that is available without undue cost or effort, that is indicative of significant increases in credit risk since initial recognition."*


  $\to$ As per [@Moody16], when comparing the lifetime default risk, it should be based on the same time frame, i.e. the remaining expected life of the loan. For example, for a 10 year mortgage that has 7 years remaining at the reporting date, we should not be comparing the expected lifetime default risk for the remaining life at reporting date (7 years remained) to the expected lifetime default risk at origination (10 years remained). That will be comparing apple to orange. Instead, we should compare the expected lifetime default risk for the remaining at reporting date to the expected default risk from 4th to 10th years with the at origination information.

* **Low credit risk simplification**, i.e. the entity can still be classified as stage 1 if it is considered low risk provided the credit risk has increased since initial recognision.

  $\to$ see [@IFRS9] 5.5.10: "*An entity may assume that the credit risk on a financial instrument has not increased significantly since initial recognition if the financial instrument is determined to have low credit risk at the reporting date (see paragraphs B5.5.22`–`B5.5.24*)."
  
* **Regular monitoring and review** should be performed for the criteria for SICR (stage 2 classification).

  $\to$ see [@IFRS9] B5.5.52: "*Historical information is an important anchor or base from which to measure expected credit losses.... An entity shall regularly review the methodology and assumptions used for estimating expected credit losses to reduce any differences between estimates and actual credit loss experience.*"
  
* **Timely recognision** of significant increase in credit risk. 

  $\to$ see [@IFRS9] B5.5.7:"*The assessment of whether lifetime expected credit losses should be recognised is based on significant increases in the likelihood or risk of a default occurring since initial recognition (irrespective of whether a financial instrument has been repriced to reflect an increase in credit risk) instead of on evidence of a financial asset being credit-impaired at the reporting date or an actual default occurring. Generally, there will be a significant increase in credit risk before a financial asset becomes credit-impaired or an actual default occurs.*"

  $\to$ see [@EBA1706] 92: "*Where a credit institution originates high-credit-risk exposures (which should not be understood, in the context of this paragraph, as meaning the opposite of ‘low credit risk’ exposures as described by IFRS 9, paragraph 5.5.10) and their allowances are initially measured at 12-month ECL, the credit institution should monitor these exposures closely for significant increases in credit risk to ensure a timely movement of the exposure to lifetime ECL measurement, in order to take into account that high risk exposures are likely to exhibit greater volatility and to experience a more rapid increase in credit risk*"
  
  $\to$ this can be interpreted by how well the stage 2 classification predict the future default (e.g. in the next 12 months if the economic outlook does not deteriorate mainly on the period beyond 12 months). If the thresholds for SICR work well, the majority of the default (stage 3) should come from stage 2. 
  
* **Relevant information in assessing changes in credit risk may pertain:** price indicators, changes in offer, external market indicators, external credit rating, actual or expected internal credit rating downgrade, significant change in collaterial value, past due information and etc.

  $\to$ see [@EBA1706] B5.5.17: 
  <details>
<summary>
<a class="btnfire small stroke"><em class="fas fa-chevron-circle-down"></em>&nbsp;&nbsp;Show All Details of B5.5.17</a>    
</summary>
 "*The following non-exhaustive list of information may be relevant in assessing changes in credit risk*:
    * *Significant changes in internal **price indicators** of credit risk as a result of a change in credit risk since inception, including, but not limited to, the credit spread that would result if a particular financial instrument or similar financial instrument with the same terms and the same counterparty were newly originated or issued at the reporting date.*
    * *Other **changes in offer** such as the rates or terms of an existing financial instrument that would be significantly different if the instrument was newly originated or issued at the reporting date (such as more stringent covenants, increased amounts of collateral or guarantees, or higher income coverage) because of changes in the credit risk of the financial instrument since initial recognition*
    * *significant changes in **external market indicators** of credit risk for a particular financial instrument or similar financial instruments with the same expected life. Changes in market indicators of credit risk include, but are not
limited to:*

      * *the credit spread;*
      * *the credit default swap prices for the borrower;*
      * *the length of time or the extent to which the fair value of a financial asset has been less than its amortised cost; *
      * other market information related to the borrower, such as changes in the price of a borrower’s debt (e.g. **bond**) and **equity instruments**.
  * *an actual or expected significant change in the financial instrument’s **external credit rating***.
  * *an actual or expected **internal credit rating downgrade** for the borrower or decrease in behavioural scoring used to assess credit risk internally. Internal credit ratings and internal behavioural scoring are more reliable when they are mapped to external ratings or supported by default studies.*
  * *existing or forecast adverse changes in business, financial or economic conditions that are expected to cause a significant change in the borrower’s ability to meet its debt obligations, such as an actual or expected increase in **interest rates** or an actual or expected significant increase in **unemployment rates***
  * *an actual or expected significant change in the **operating results** of the borrower. Examples include actual or expected declining revenues or margins, increasing operating risks, working capital deficiencies, decreasing asset quality, increased balance sheet leverage, liquidity, management problems or changes in the scope of business or organisational structure (such as the discontinuance of a segment of the business) that results in a significant change in the borrower’s ability to meet its debt obligations.*
  * *significant increases in credit risk on other financial instruments of the same borrower*
  * *an actual or expected significant adverse change in the **regulatory**, economic, or **technological environment** of the borrower that results in a significant change in the borrower’s ability to meet its debt obligations, such as a decline in the demand for the borrower’s sales product because of a shift in technology.*
  * *significant changes in the value of the **collateral** supporting the obligation or in the quality of third-party guarantees or credit enhancements, which are expected to reduce the borrower’s economic incentive to make scheduled contractual payments or to otherwise have an effect on the probability of a default occurring. **For example, if the value of collateral declines because house prices decline, borrowers in some jurisdictions have a greater incentive to default on their mortgages.***
  * *a significant change in the quality of the guarantee provided by a shareholder (or an individual’s parents) if the shareholder (or parents) have an incentive and financial ability to prevent default by capital or cash infusion*
  * *significant changes, such as reductions in financial support from a parent entity or other affiliate or an actual or expected significant change in the quality of credit enhancement, that are expected to reduce the borrower’s
economic incentive to make scheduled contractual payments. Credit quality enhancements or support include the consideration of the financial condition of the guarantor and/or, for interests issued in securitisations, whether subordinated interests are expected to be capable of absorbing expected credit losses (for example, on the loans underlying the security).*
  * *expected changes in the loan documentation including an expected breach of contract that may lead to covenant waivers or amendments, interest payment holidays, interest rate step-ups, requiring additional collateral or guarantees, or other changes to the contractual framework of the instrument.*
  * *significant changes in the expected performance and behaviour of the borrower, including changes in the payment status of borrowers in the **group** (for example, an increase in the expected number or extent of delayed contractual payments or significant increases in the expected number of credit card borrowers who are expected to approach or exceed their credit limit or who are expected to be paying the minimum monthly amount).*
  * *changes in the entity’s credit management approach in relation to the financial instrument; ie based on emerging indicators of changes in the credit risk of the financial instrument, the entity’s credit risk management practice is expected to become more active or to be focused on managing the instrument, including the instrument becoming more closely monitored or controlled, or the entity specifically intervening with the borrower.*
  * ***past due information**, including the rebuttable presumption as set out in paragraph*"

</details>
  
  
 

### 3. Probability Weighted Scenarios


* The ECL should be based on a range of possible outcomes weighted by the unbiased probability of occurance.

  $\to$ see [@EBA1706] 5.5.17:"	
An entity shall measure expected credit losses of a financial instrument in a way that reflects:
  * an unbiased and probability‑weighted amount that is determined by evaluating a range of possible outcomes;
  * the time value of money; and
  * reasonable and supportable information that is available without undue cost or effort at the reporting date about past events, current conditions and forecasts of future economic conditions."
  
  
### 4. Other points

  
* The remaining lifetime cannot exceed the contractual maturity. Essentially, the multi-year ECL is 0 beyond the contractual maturity.

  $\to$ see [@EBA1706] 5.5.19: The maximum period to consider when measuring expected credit losses is the maximum contractual period (including extension options) over which the entity is exposed to credit risk and not a longer period, even if that longer period is consistent with business practice.
  


### 6. References
  
  
  

