---
title: "Calculus Integration Techniques"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    includes:
       in_header: GA_Script.html
---

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### u Substitution
</ins>
</div>

**Theorem:**  
$$\int f(g(x))g'(x)dx = \int fudu$$
where $u = g(x)$

**Proof:**  
Let $F(u)$ be an antiderivative for $f(u)$ and $u = g(x)$
then $\frac{dF(u)}{du} = f(u)$, and $\frac{dF(u)}{dx} = \frac{dF(u)}{du} \cdot \frac{du}{dx} = f(g(x))g'(x)$
$\Rightarrow \int \frac{dF(u)}{dx} dx = \int f(g(x))g'(x) dx$

**Example 1.** $\int (x^2-1)^42xdx$  
Let $u = x^2-1$, then $\frac{du}{dx} = 2x$,  
then $\int (x^2-1)^42xdx = \int u^4 \frac{du}{dx}dx = \int u^4du = \frac{1}{5}u^5 = \frac{1}{5}(x^2-1)^5+C$  

**Example 2.** $\int sin(x)cos(x)dx$  
Let $u = sin(x)$, then $\frac{du}{dx} = cos(x)$,  
then $\int u\frac{du}{dx} = \int u \ du = \frac{1}{2}u^2+C = \frac{1}{2}sin^2(x)+C$

**Example 3.** $\int \frac{1}{(3+5x)^2}dx$  
Let $u = 3+5x$, then $\frac{du}{dx} = 5$,  
then $\int \frac{1}{(3+5x)^2}dx = \frac{1}{5} \int \frac{1}{u^2}\frac{du}{dx}dx = \frac{1}{5}\cdot (-1) u^{-1}+C=\frac{-1}{5}\cdot \frac{1}{3+5x}+C$




<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Integration by Parts
</ins>
</div>

**Theorem:**  
$$\int_a^b f(x)g'(x)dx = f(x)g(x)\ |_a^b-\int_a^b f'(x)g(x)dx$$

**Proof:**  
This is derived from the rule of multiplication of taking derivatives

$\because[f(x)g(x)]' = f'(x)g(x)+f(x)g'(x)$
$\therefore \int f(x)g'(x)dx = f(x)g(x)-\int f'(x)g(x)dx$

**Example 1.** $\int xe^x\ dx$  
Let $f(x) = x$ and $g'(x) = e^x$  
then $\int xe^x\ dx = xe^x - \int 1 \cdot e^x\ dx = xe^x - e^x +C$

**Example 2.** $\int x^3ln(x)\ dx$  
Let $f(x) = x^3$ and $g'(x) = ln(x)$  
then $\int x^3ln(x)\ dx = \int ln(x)x^3\ dx = ln(x)\cdot\frac{1}{4}x^4 - \int \frac{1}{x} \frac{1}{4}x^4\ dx = \frac{1}{4}ln(x)x^4 - \frac{1}{20}x^5 + C$




<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Trigonometric Substitution
</ins>
</div>

Integrals involving $\sqrt{a^2+x^2}$ or $\sqrt{x^2-a^2}$, use trigonometric substitution

**Example 1.** $\int \frac{1}{(9-x^2)^{3/2}}\ dx$  
Let $x = 3sin(u)$, then $\frac{dx}{du} = 3cos(u)$ and  
$\int \frac{1}{(9-x^2)^{3/2}}\ dx = \int \frac{1}{(9sin^2(u))^{3/2}}\cdot 3cos(u)\ du = \frac{1}{9}tan(u)+C = \frac{1}{9}\frac{x}{\sqrt{9-x^2}}+C$



<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Partial Fractions
</ins>
</div>


