---
title: "Ito's Lemma & Stochastic Calculus"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Derive Ito's Lemma
</ins>
</div>
Recall that the **Chain Rule** for non-stochastic functions:

$$
\begin{aligned}
\frac{d}{dx}f(g(x)) &= f'(g(x))g'(x) \\
&= f'(g(x))dg(x)
\end{aligned}
$$




where $f$ and $g$ are differentiable. It can also be expressed as 

$$\frac{dz}{dx} = \frac{dz}{dy} \cdot \frac{dy}{dx}$$
where $y$ is a function of $x$ and $z$ is a function of $y$.

Extended to integral:

$$\int_a^bf(g(x))g'(x)dx = \int_{g(a)}^{g(b)} f(u)du = \int_a^bf(g(x))dg(x)$$
where $u = g(x)$

However, all of the above only works when function $g$ is differentiable. In a case where $g(t) = W(t)$ which is a Brownian motion, a non-differentiable function, we can't use the Chain Rule as described but we need a new rule. 

Luckily **Taylor's Expansion** come to save us. The Taylor's Expansion is:

$$
\begin{aligned}
d(f(g(t))) &= f(g(t)+dg(t)) - f(g(t)) \\
&= f'(g(t))dg(t) + \frac{1}{2}f^{(2)}(g(t)) \cdot [dg(t)]^2 + ..\frac{1}{k!}f^{(k)}(g(t)) \cdot [dg(t)]^k + ...
\end{aligned}
$$

Plug in $g(t) = W(t)$ and ignoring the higher order terms ($k>=3$), then we can get the **Ito's Lemma**:

$$
\begin{aligned}df(W(t)) &= f(W(t)+dW(t)) - f(W(t)) \\
&= f'(W(t))dW(t) + \frac{1}{2} f^{(2)}(W(t))[dW(t)]^2\\
&= f'(W(t))dW(t) + \frac{1}{2} f^{(2)}(W(t))dt \\
\end{aligned}
$$

The 3rd step of the above equation is an important property of the Wiener process and will be shown in the following paragraph.

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Wiener Process
</ins>
</div>

Properties of Wiener Process:

* $W_0 = 0$
* $W_n = W_0 + \sum_{t=1}^n \Delta W_t$
* Increments $\Delta W_t$ are i.i.d. and $W_t-W_s \sim \mathcal{N}(0,t-s)$ where $t-s$ is the variance

Given that $t_0 = 0 < t_1 < t_2 < ...t_n = t$ and $t_{i}-t_{i-1} = \frac{t}{n}$ and $n \to \infty$
then
$$W_{t_i}-W_{t_{i-1}} \sim \mathcal{N}(0,\frac{t}{n})$$

$$\int_0^tdW_{t_i} = \sum_{i=0}^{n}(W_{t_i}-W_{t_{i-1}})$$


$$
\begin{aligned}
\int_0^t(dW_s)^2 &= \sum_{i=0}^{n}(W_{t_i}-W_{t_{i-1}})^2 \\
& \overrightarrow{n \to \infty} \ \ n \cdot E[(W_{t_i}-W_{t_{i-1}})^2]\\
&= n \cdot Var(W_{t_i}-W_{t_{i-1}}) \\
&= n \cdot \frac{t}{n} = t\\
\end{aligned}
$$

By taking the derivative, we can derive that $(dW_t)^2 = dt$
