---
title: "Measure Theory"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Sigma Algebra
</ins>
</div>

$X$ set

$\mathcal{P}(X)$ power set of X


**Example**: $X = \{a, b\}$, then $\mathcal{P}(X) = \{\phi, X, \{a\}, \{b\} \}$

**Definition**: $\mathcal{A} \subseteq P(X)$ is called a $\sigma$ -algebra if it satisfies:

* $\phi, X \in \mathcal{A}$  
* $A \in \mathcal{A}$ => $A^c \in \mathcal{A}$  
* $A_i \in \mathcal{A}, \ i \in \mathbb{N}$ => $\bigcup_{i=1}^{\infty} A_i \in \mathcal{A}$

$A \in \mathcal{A}$ is called a $\mathcal{A}$-measurable set.

**Example**:

* $\mathcal{A}=\{\phi, X\}$
* $\mathcal{A} = \mathcal{P}(X)$

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Borel Sigma Algebra
</ins>
</div>

**Definition**: For $\mathcal{M} \in \mathcal{P}(X)$, there is a smallest $\sigma$-algebra that contains $\mathcal{M}$:

$\sigma(\mathcal{M}):=\bigcap_{\mathcal{A} \subseteq \mathcal{M}} \mathcal{A}$

**Example**: $X = \{a,b,c,d\}$, $\mathcal{M} = \{\{a\},\{b\}\}$  
The most effieicnt $\sigma$-algebra (with the smallest set)$\sigma(\mathcal{M}) = \{\phi, X,\{a\},\{b\}, \{a,b\}, \{b,c,d\},\{a,c,d\}, \{c,d\}$

It is difficult if the set X is infinity


**Definition**: Let X be a topological (or metric, or $\mathbb{R^n}$) space:  
  $\mathcal{B}(X)$ Borel $\sigma$-algebra on X (the $\sigma$-algebra generated by the open sets) 
  $\mathcal{B}(X):=\sigma(\mathcal{T})$  
  Borel $\sigma$-algebra is not the power set

**Definition**: $(X, \mathcal{A})$ measurable space (a $\sigma$-algebra in set X)  
  A map $\mathcal{M}:\mathcal{A}$ -> $[0,\infty]$ is called a measure if it satisfies  
  
  * $\mathcal{M}(\phi)=0$  
  * $\mathcal{M}(\bigcup_{i=1}^{\infty} A_i) = \sum_{i=1}^{\infty} \mathcal{M}(A_i)$, with $A_i \bigcap A_j = \phi$ (**additive**)

$(X, \mathcal{A}, \mathcal{M})$ measure space

**Examples**: $X$, $\mathcal{A}= \mathcal{P}(X)$  

* Counting measure
* Dirac measure


**Measure problem**: Search measure $\mathcal{M}$ on $\mathcal{P}(\mathbb{R})$ with:

* $\mathcal{M}([a,b])=b-a$
* $\mathcal{M}(X+A) = \mathcal{M}(A)$, $A \in \mathcal{P}(\mathbb{R})$  
=> $\mathcal{M}$ does not exist.

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Measurable Maps
</ins>
</div>

**Definition**: $(\Omega_1, \mathcal{A}_1)$, $(\Omega_2, \mathcal{A}_2)$ measurable space  
$f: \Omega_1 \to \Omega_2$ measurable (w.r.t. $\mathcal{A}_1)$, $\mathcal{A}_2)$)

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### Lebesgue Integral
</ins>
</div>

