---
title: "Recommendation Systems"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
bibliography: references.bib
link-citations: yes
---

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### 1. Similarities
</ins>
</div>

For 2 vectors $q$ and $x$

* cosine: $cos(q,x)$
* dot product: $\lVert q \lVert \lVert x \lVert cos(q,x)$
* Euclidean distance: $\lVert q-x \lVert$

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### 2. Content Based Recommendations
</ins>
</div>

The similarity measures can be use for content based filtering. When recommending a movie to a user, the similarity score is compared between the user and the movie. It is surprising to treat movie and user with the same feature space since they are 2 different kind of entities. This is just a way to measure relevance.

We can treat each user as a separate linear regression problems by following the below steps:

* Manually give each movie a score for each feature selected (e.g. romance, action)
* For each user $j$, learn parameter $\theta^{(j)} \in 	\mathbb{R}^{n+1}$, where $n$ is the number of features
* Predict user $j$ as rating movie $i$ with $(\theta^{(j)})^T x^{(i)}$

This means that each user has their own method (represented by different linear function) of rating the movies by taking the variables $X$ as inputs.

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### 3. Collaborative Filtering
</ins>
</div>


<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### 4. Matrix Factorization
</ins>
</div>

When recommending a movie, the algorithm should recommend

* movies similar to the ones that user has liked in the past
* movies that similar users liked

Again, both movies and users are represented in the same embedding space.

The goal is to factorize the feedback matrix $A$ into the product of a user embedding matrix $U$ and item (movie) embedding matrix $V$ such that $A	\approx UV^T$

* user $U \in \mathbb{R}^{m {\times} d}$
* item $V \in \mathbb{R}^{n {\times} d}$

where $m$ is the number of user, $n$ is the number of items and $d$ is the number of dimensions (features/variables)

Matrix factorization, $UV^T$ is a simple embedding model

Choosing the Objective Function

* Observing only MF
* Weighted MF
* Singular Value Decomposition (SVD)

Minimizing the Objective Function

* Stochastic gradient descent (SGD) 
* Weighted Alternating Least Squares (WALS)

$\to$ cold-start problem

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### 4. References
</ins>
</div>

<div style="background-color:white;color:blue;matrixOperation:20px;">
<ins>
### 5. Terminology 
</ins>
</div>

* Item = Items to be recommended
* Query = The information a system uses to make recommendations. e.g. items previously interact with, time of day, the user's device
* Embedding = A mapping from a discrete set (in this case, the set of queries, or the set of items to recommend) to a vector space called the embedding space. 

